version: '3.8'

services:
  ble-simulator:
    image: crpi-qqo05szhq6ruqonk.cn-hangzhou.personal.cr.aliyuncs.com/hjw2727/ble_simulator:latest
    container_name: ble_simulator
    command: bash -c "source /opt/venv/bin/activate && python3 src/python/run_server.py"
    # command: tail -f /dev/null
    tty: true
    stdin_open: true
    privileged: true
    network_mode: host
    volumes:
      - ../:/app
      - /sys/bus/usb:/sys/bus/usb:ro
      - /dev/bus/usb:/dev/bus/usb
      - /var/run/dbus:/var/run/dbus
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    environment:
      - TERM=xterm-256color
    working_dir: /app
    restart: unless-stopped